export const partnersList = [
  {
    image:
      "https://img.freepik.com/premium-vector/university-campus-logo_1447-1793.jpg",
  },
  {
    image:
      "https://image.freepik.com/free-vector/campus-collage-university-education-logo-design-template_7492-63.jpg",
  },
  {
    image:
      "https://image.freepik.com/free-vector/campus-collage-university-education-logo-design-template_7492-62.jpg",
  },
  {
    image:
      "https://img.freepik.com/premium-vector/university-campus-logo_1447-1790.jpg",
  },
  {
    image:
      "https://image.freepik.com/free-vector/campus-collage-university-education-logo-design-template_7492-64.jpg",
  },
];